### ISSUE TITLE
Update to 18.1

### ISSUE THREAD

**Issue by michaelklishin** [jasonmcintosh/esl-erlang-compat#2]
Would it be possible to update this package to OTP 18.1?

**Comment by jasonmcintosh** [comment]
Doing now :)

**Comment by jasonmcintosh** [comment]
Committed, latest release published as 1.1.0  

https://github.com/jasonmcintosh/esl-erlang-compat/releases/tag/1.1.0

https://github.com/jasonmcintosh/esl-erlang-compat/releases/download/1.1.0/esl-erlang-compat-R1801-1.noarch.rpm

**Comment by jasonmcintosh** [comment]
Hrmm, I'll probably update this - I missed how they're setting the version number.  Wonder if that changed from the older R\* releases.  Updating the release with the updated versions now.

**Comment by jasonmcintosh** [comment]
OK fixed in 1.1.1 release.
https://github.com/jasonmcintosh/esl-erlang-compat/releases/tag/1.1.1
https://github.com/jasonmcintosh/esl-erlang-compat/releases/download/1.1.1/esl-erlang-compat-18.1-1.noarch.rpm

**Comment by michaelklishin** [comment]
@jasonmcintosh thank you so much!
