### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by BMillsVT** [jasonmcintosh/esl-erlang-compat#5]
Jason, 
The header for the "esl-erlang-compat.spec" file lists MPLv.1.1, MIT, ASL 2.0, and BSD as the license for the file. I assume that means the entire esl-erlang Shim Package is licensed in the same way.  Can you clarify what license(s) applies and/or add a license.txt file to the repo?  The MIT license, for example, specifically states that the license text must accompany the source code.  

Thanks,
Brian

**Comment by jasonmcintosh** [comment]
This library which just basically allows the RPM database to provide erlang when you have esl-erlang is open source as in "Use it to your hearts content".  I'll add a license, but I mostly consider this as "take your pick, commercial, not, internal, release for others, etc."

**Comment by BMillsVT** [comment]
Thanks Jason.  Not having a license clearly specified makes it difficult for others (especially corps with a bunch of lawyers) to utilize your code. I'd recommend the MIT license - it's one of the easiest with which to comply.

**Comment by jasonmcintosh** [comment]
License file included in the project :)  If you want it in the RPM I can look at having that done as well.
