### ISSUE TITLE
Erlang 20.3.8.20 and 21.2.6

### ISSUE THREAD

**Issue by michaelklishin** [jasonmcintosh/esl-erlang-compat#8]
Recent RabbitMQ 3.7 releases only support Erlang 20.3 and 3.8 will require 21.2. Would it be possible to produce and upload binaries for `20.3.8.20` and `21.2.6`, for example? I understand that the functionality of this package doesn't really change between versions, it's mostly to avoid confusing the user.

Thank you!

**Comment by jasonmcintosh** [comment]
Sorry for delay on this - note @michaelklishin you've got permissions to do this yourself ;) BUT will work on updating it :)

**Comment by jasonmcintosh** [comment]
Done and releases updated.  Also updated to use docker builder - SHOULD make it easier to use going forward :)
